### PR TITLE
Preselected options should be rendered

### PR DESCRIPTION
**Pull request by codazzo**
Options can be selected by setting the `selected` property onto
their respective DOM elements.
If an option has a 'selected' attribute, the browser will set
the corresponding DOM property: the fix therefore works in both cases.

I've been unable to run the tests locally so I'm hoping this will be green @grahamscott

### CODE REVIEW

**Comment by superneko** [comment]
@codazzo Could you have a look at this again? It's seems to be red and angry.

**Comment by spmason** [comment]
The recent merge of the changes for v2 probably broke this

**Comment by superneko** [comment]
p00p.

**Comment by grahamscott** [comment]
@codazzo does the problem still exist in v2?

**Comment by codazzo** [comment]
> Could you have a look at this again? It's seems to be red and angry.
> The recent merge of the changes for v2 probably broke this

Unfortunately I'm not able to run the tests locally (am I the only one?) so can't really tell why they're breaking

> @codazzo does the problem still exist in v2?
Yes, just tried

On a related note, we should get rid of `dist/` with priority as it makes rebasing (and making changes to a PR) quite painful. The options are: `dist` branch, or bundles on bower / npm. Either way the bundles would need to be kept up to date by a travis task. I will create an issue.

**Comment by codazzo** [comment]
Opened https://github.com/BrandwatchLtd/selleckt/issues/73

**Comment by grahamscott** [comment]
superceded by https://github.com/BrandwatchLtd/selleckt/pull/84

**Pull request closed without merging**
